//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TrafficLightImage
{
    [Serializable]
    public class BinaryImageMsg : Message
    {
        public const string k_RosMessageName = "traffic_light_image/BinaryImage";
        public override string RosMessageName => k_RosMessageName;

        public byte[] data;
        public uint width;
        public uint height;
        public string encoding;

        public BinaryImageMsg()
        {
            this.data = new byte[0];
            this.width = 0;
            this.height = 0;
            this.encoding = "";
        }

        public BinaryImageMsg(byte[] data, uint width, uint height, string encoding)
        {
            this.data = data;
            this.width = width;
            this.height = height;
            this.encoding = encoding;
        }

        public static BinaryImageMsg Deserialize(MessageDeserializer deserializer) => new BinaryImageMsg(deserializer);

        private BinaryImageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.width);
            deserializer.Read(out this.height);
            deserializer.Read(out this.encoding);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
            serializer.Write(this.width);
            serializer.Write(this.height);
            serializer.Write(this.encoding);
        }

        public override string ToString()
        {
            return "BinaryImageMsg: " +
            "\ndata: " + System.String.Join(", ", data.ToList()) +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString() +
            "\nencoding: " + encoding.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
